security:
    providers:
        agenciaVuelos_usuarios:
            entity:
                class: App\Entity\Usuario
                property: email
    password_hashers:
        App\Entity\Usuario:
            algorithm: auto
            ignore_case: true
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: agenciaVuelos_usuarios
            user_checker: App\Security\UserChecker
            form_login:
                login_path: ctrl_login
                check_path: ctrl_login
                default_target_path: ctrl_home
            logout:
                path:   ctrl_logout
                target: ctrl_login
            